---
title: "DataRes Winter - UFC Viz & Player analysis"
author: "Hana Yerin Lim"
date: "1/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(ggplot2)
library(dplyr)
info <- read_csv("C:\\Users\\pione\\OneDrive\\Documents\\Project\\Datares\\team-octagoners\\Data Source\\ufc-master.csv")
past_events <- read_csv("C:\\Users\\pione\\OneDrive\\Documents\\Project\\Datares\\team-octagoners\\Data Source\\most-recent-event.csv")
future_events <- read_csv("C:\\Users\\pione\\OneDrive\\Documents\\Project\\Datares\\team-octagoners\\Data Source\\upcoming-event.csv")
info
past_events
future_events
```

```{r}
dim(info)
```
4558 observations and 137 columns in player's information dataset 

# Data Manipulation  
```{r}
library(chron)
library(lubridate)
# Change character date into date format 
info$date <- as.Date(info$date, "%m/%d/%Y")
# Add a binary column of Weekend events 
info$isWeekend <- is.weekend(info$date)
# Add a column containing days 
info$days <- weekdays(as.Date(info$date))
# add a column with months
info$month <- month(ymd(info$date))
info$month <- month.abb[info$month]
info$year <- year(ymd(info$date))
info <- info[, -match("constant_1", names(info))]

rearrange <- info %>% gather(class, rank, `R_Women's Flyweight_rank`:`B_Pound-for-Pound_rank`)
newdata <- rearrange[-which(is.na(rearrange$rank)), ]
newdata$rank <- as.factor(newdata$rank)
```

# months heatmap 
```{r}
library(wesanderson)
info$month <- factor(info$month, levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun","Jul","Aug","Sep","Oct","Nov","Dec"))
my <- info %>% group_by(month, year) %>% summarise(n = n()) 
ggplot(my) + geom_tile(aes(x = month, y = year, fill = n)) +
  scale_fill_viridis_c() + 
  scale_y_continuous("year", labels = as.character(2010:2021), breaks = 2010:2021) +
  ggtitle("Heatmap of frequencies of the game for the past decade") + 
  theme(plot.title = element_text(hjust = 0.5, size = 14))

# Pandemic game state 
info %>% filter(year == 2020 & month != "Jan" & month != "Feb" & month != "Mar") %>% group_by(month) %>% summarise(count = n())
```

# Most Frequent players 
```{r}
#jul_2016 <- info %>% filter(year == 2016, month == "Jul")
R_freq <- info %>% group_by(R_fighter) %>% summarise(count = n()) %>% arrange(desc(count))
ggplot(R_freq[1:10, ], aes(x = reorder(R_fighter, count), y = count, fill = count)) + geom_bar(stat = "identity") + 
  coord_flip() + scale_fill_viridis_c(option = "magma", direction = -1) +
  xlab("R_Fighters") + ylab("Count of participation") + 
  ggtitle("Top 10 Red players with the most frequent participant") + 
  theme(plot.title = element_text(hjust = 0.5))

B_freq <- info %>% group_by(B_fighter) %>% summarise(count = n()) %>% arrange(desc(count))
ggplot(B_freq[1:10, ], aes(x = reorder(B_fighter, count), y = count, fill = -count)) + geom_bar(stat = "identity") + 
  coord_flip() + scale_color_gradient("Blues") +
  xlab("B_Fighters") + ylab("Count of participation") + 
  ggtitle("Top 10 Blue players with the most frequent participant") + 
  theme(plot.title = element_text(hjust = 0.5))
```

# Red/Blue winner proportion 
```{r}
info %>% group_by(Winner) %>% summarise(n = n()) %>% ungroup() %>% mutate(prop = n/sum(n)) %>% 
  ggplot(aes(x = "", y = prop, fill = Winner)) + geom_bar(stat = "identity", color = "white") + 
  coord_polar("y", start = 0) + 
  geom_text(aes(label = paste0(round(prop, 3)*100, "%")), position = position_stack(vjust = 0.5)) + 
  scale_fill_manual(values = c("royalblue2", "firebrick3"))+ 
  theme(axis.text = element_blank(), axis.ticks = element_blank(), panel.grid = element_blank(), plot.title = element_text(hjust =0.5)) + 
  ggtitle("Proportion of Red/Blue Winners")
```

# top red/blue players with the most win streaks 
```{r}
B_high_winstreak <- newdata %>% arrange(desc(B_current_win_streak)) %>% filter(B_current_win_streak > 5) 
ggplot(B_high_winstreak[c(1:3,5:11,13:17),], aes(x = reorder(B_fighter, B_current_win_streak), y = B_current_win_streak, fill = weight_class)) + 
  geom_bar(stat = "identity") + 
  coord_flip() + 
  geom_text(aes(label = B_current_win_streak), hjust=1.5) + 
  theme(plot.title = element_text(hjust =0.5)) + 
  ylab("B_fighter") +
  ggtitle("Top 15 Blue players with the most win streaks")

B_team_top_players <- B_high_winstreak[c(1:3,5:11,13:17), ]
B_team_top_players <- select(B_team_top_players, contains("B_"))

R_high_winstreak <- newdata %>% arrange(desc(R_current_win_streak)) %>% filter(R_current_win_streak > 5) 
ggplot(R_high_winstreak[c(1:2,6:7,9:10, 15, 21, 23, 31, 37, 39, 42, 43, 45),], aes(x = reorder(R_fighter, R_current_win_streak), y = R_current_win_streak, fill = weight_class)) + 
  geom_bar(stat = "identity") + 
  coord_flip() + 
  geom_text(aes(label = R_current_win_streak), hjust=1.5) + 
  theme(plot.title = element_text(hjust =0.5)) + 
  ylab("B_fighter") +
  ggtitle("Top 15 Blue players with the most win streaks")

R_team_top_players <- R_high_winstreak[c(1:2,6:7,9:10, 15, 21, 23, 31, 37, 39, 42, 43, 45), ]
R_team_top_players <- select(R_team_top_players, contains("R_"))

test <- cbind(B_team_top_players,R_team_top_players)

```

# IsWeekend 
```{r}
info %>% group_by(isWeekend) %>% summarise(count = n()) %>% ungroup() %>% mutate(prop = count/sum(count)) %>%
  ggplot(aes(x = "", y = prop, fill = isWeekend)) + geom_bar(stat = "identity", color = "white") + 
  coord_polar("y", start = 0) +
  geom_text(aes(label = paste0(round(prop, 3)*100, "%")), position = position_stack(vjust = 0.5)) +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), panel.grid = element_blank()) + 
  ggtitle("Proportion of Weekends and Weekdays Games")
```

# days 
```{r}
info %>% group_by(days, isWeekend) %>% summarise(n = n()) %>% 
  ggplot(aes(x = days, y = n, fill = isWeekend)) + geom_bar(stat = "identity") + 
  ggtitle("Barplot of days of the games")
```




